CREATE TABLE RECORD (
	idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '인덱스',
	user INT NOT NULL COMMENT '사용자 인덱스',
	speed INT NOT NULL COMMENT '속도',
	date DATE NOT NULL COMMENT '날짜'
) COMMENT '기록';

SELECT * FROM RECORD;