CREATE TABLE SHORT (
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
	name VARCHAR(255) NOT NULL COMMENT '말한 사람 이름',
	short TEXT NOT NULL COMMENT '짧은 글'
) COMMENT '짧은 글';

SELECT * FROM SHORT;

DROP TABLE SHORT;