CREATE TABLE USER (
	idx INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '인덱스',
	id VARCHAR(255) NOT NULL COMMENT '아이디',
	password VARCHAR(255) NOT NULL COMMENT '비밀번호'
) COMMENT '사용자';

TRUNCATE USER;

SELECT * FROM USER;